---
version: '3'
services:
  dvwa:
    image: wallarm/fast-example-dvwa-base
    networks:
      main:
        aliases:
          - dvwa

  fast:
    image: wallarm-dkr-dev.jfrog.io:443/wallarm-fast-node:feature-FAST-1866-ll-pipelines
    environment:
      WALLARM_API_TOKEN: ${WALLARM_API_TOKEN}
      CI_MODE: recording
      ALLOWED_HOSTS: dvwa
      BUILD_ID: ${BUILD_TAG}
      WALLARM_API_HOST: 51.68.93.197
      WALLARM_API_PORT: 9752
      WALLARM_API_USE_SSL: "false"
      WALLARM_API_CA_VERIFY: "false"
    networks:
      main:
        aliases:
          - fast

  selenium:
    image: selenium/standalone-firefox:latest
    logging:
      driver: none
    environment:
      http_proxy: http://fast:8080
    networks:
      main:
        aliases:
          - selenium

  test:
    image: wallarm/fast-example-dvwa-tests
    networks:
      main:

networks:
  main:
