---
version: '3'
services:
  dvwa:
    image: wallarm/fast-example-dvwa-base
    networks:
      my_test1:
        aliases:
          - dvwa

  selenium:
    image: selenium/standalone-firefox:latest
    environment:
      http_proxy: http://Fast123:3128
    networks:
      my_test1:
        aliases:
          - selenium

  test:
    image: wallarm/fast-example-dvwa-tests
    networks:
      my_test1:
        aliases:
          - test_container_alias
networks:
  my_test1:
