---
version: '3'
services:
  dvwa:
    image: wallarm/fast-example-dvwa-base
    networks:
      main:
        aliases:
          - dvwa

  selenium:
    image: selenium/standalone-firefox:latest
    logging:
      driver: none
    environment:
      http_proxy: http://fast:8080
    networks:
      main:
        aliases:
          - selenium

  test:
    image: wallarm/fast-example-dvwa-tests
    networks:
      main:
